FROM apache/airflow:2.7.1

USER airflow

RUN pip install --no-cache-dir \
    "numpy==1.24.4" \
    "pandas==2.0.3" \
    "scikit-learn==1.3.2" \
    "xgboost==1.7.6" \
    "matplotlib==3.7.5" \
    "seaborn==0.13.2" \
    "mlflow==2.7.1" \
    "joblib==1.3.2"